# dup.toml
[scan]
roots = ["data/samples"]
follow_symlinks = false
ignore_hidden = true
include_ext = [".jpg", ".jpeg", ".heic", ".mov", ".cr2", ".nef", ".arw", ".dng"]
db_path = ".pdai/index.sqlite3"
